// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function($scope) {
    var Base;
    Base = moment("20131003", "YYYYMMDD").endOf('day');
    $scope.time = Base.fromNow();
    return setInterval(function() {
      return $scope.$apply(function() {
        return $scope.time = Base.fromNow();
      });
    }, 60 * 60 * 1000);
  };

  angular.module('marriageApp').controller('MainCtrl', ['$scope', controller]);

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
