// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function($scope) {
    $scope.days = 0;
    $scope.hours = 0;
    return $scope.minutes = 0;
  };

  angular.module('marriageApp').controller('MainCtrl', ['$scope', controller]);

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
