// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('marriageApp', []).config(function($routeProvider) {
    return $routeProvider.when('/', {
      templateUrl: 'views/main.html',
      controller: 'MainCtrl'
    }).otherwise({
      redirectTo: '/'
    });
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
